services:

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    command: --innodb-use-native-aio=0
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql/script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challenge-network

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- /usr/src/app/start.sh
    depends_on:
      - db
    networks:
      - challenge-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    entrypoint: wait-for app:3000 -t 40 -- nginx -g "daemon off;"
    depends_on:
      - app
    networks:
      - challenge-network
    ports:
      - "8080:80"

networks:
  challenge-network:
    driver: bridge
